// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMrtouhL8pbw_SrclivdYXINCiZ5i_Y3w',
    appId: '1:778051585993:web:ed677b5f583d7716234a18',
    messagingSenderId: '778051585993',
    projectId: 'todolist-flutter-fc5fc',
    authDomain: 'todolist-flutter-fc5fc.firebaseapp.com',
    storageBucket: 'todolist-flutter-fc5fc.appspot.com',
    measurementId: 'G-KBGRJD3RWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq5VO2cdeoEudE6hOOUHm9XNVqWVUdrCI',
    appId: '1:778051585993:android:5795d7decaf2138a234a18',
    messagingSenderId: '778051585993',
    projectId: 'todolist-flutter-fc5fc',
    storageBucket: 'todolist-flutter-fc5fc.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMrtouhL8pbw_SrclivdYXINCiZ5i_Y3w',
    appId: '1:778051585993:web:436db9560a416131234a18',
    messagingSenderId: '778051585993',
    projectId: 'todolist-flutter-fc5fc',
    authDomain: 'todolist-flutter-fc5fc.firebaseapp.com',
    storageBucket: 'todolist-flutter-fc5fc.appspot.com',
    measurementId: 'G-QTDYVB01P0',
  );

}